apiVersion: v1.1
kind: Service
metadata:
  name: tf-model-service
  namespace: default
spec:
  selector:
    app: tf-model
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort
